spring:
  data:
    mongodb:
      host: 221.226.60.2
      port: 64785
      username: ogms
      password: ogms1qaz@wsxOGMS
      database: geodata
      authentication-database: geodata

resourcePath: /data/nnuGeoData
